### ISSUE TITLE
multiple w215's only last is used

### ISSUE THREAD

**Issue by abort-retry-ignore** [bikerp/dsp-w215-hnap#10]
I have 3 w215's setup as accessories and only the last one seems to work.  The other three register, and show up in home kit, but turning any of them on always turns the last switch on.  Same with turning it off.  

Is it a config problem or is it a limitation?  I'd appreciate any help you can offer. Here is my config:

config.json
{
     "bridge":
    {
            "name": "Homebridge",
            "username": "CC:22:3D:E3:CE:30",
            "port": 51826,
            "pin": "031-45-154"
        },

 "accessories": [
	{
        	"accessory": "w215",
        	"name": "Dlink1",
        	"host": "10.1.2.14",
        	"username": "admin",
        	"password": "**edited**"
    	},
	{
                "accessory": "w215",
                "name": "Dlink2",
                "host": "10.1.2.20",
                "username": "admin",
                "password": "**edited**"
	},
	{
                "accessory": "w215",
                "name": "Dlink3",
                "host": "10.1.2.21",
                "username": "admin",
		"password": "**edited**"
	}
	]
}

**Comment by abort-retry-ignore** [comment]
I tried making the password invalid on the first entry, and home bridge loaded without error.  I then tried making the password invalid on the last accessory entry, and it broke.  It looks like only the last accessory entry credentials and IP are being used.

**Comment by bikerp** [comment]
Hi, I think that this is not related to the code as such. You probably select wrong IP address from your config.json file as you mentioned in your last post. The code is supposed to communicate with only one socket. If you want multiple sessions you should modify the code.
Regards Pavel

**Comment by abort-retry-ignore** [comment]
Thanks for replying Pavel.  You can see from the config I posted that each switch is on a different IP with a different password.  I have verified the IPs from my router, they are setup to be static.  I can make any switch work as long as its the only one, so if its only dlink1, then it works.  If its only dlink2, it works etc.  If I put more than one switch in the config, only the last one works.  How can I modify the config file to allow for more than one switch?

**Comment by bikerp** [comment]
Hi,
as I said this code is intended to communicate with one target only. There is no config file so I can't tell what is wrong with your code. You can share your code on github and send me the link so I can take a look.
Since it is not related to my code I close the issue.
Pavel

**Comment by abort-retry-ignore** [comment]
I solved the issue by running multiple copies of homebridge, one for each switch.
