### ISSUE TITLE
Auth failed / host unreachable

### ISSUE THREAD

**Issue by teejay-87** [bikerp/dsp-w215-hnap#12]
I've been using this node plugin for almost a year, alongside with Homebridge installed on a Synology NAS in Debian Chroot sandbox.

From 2 months ago, I'm now getting this error when the plug status is requested:

```
error: { [Error: connect EHOSTUNREACH]
  code: 'EHOSTUNREACH',
  errno: 'EHOSTUNREACH',
  syscall: 'connect' }
[Mon Sep 17 2018 23:52:30 GMT+0200 (CEST)] [D-Link Smart Plug] Login failed!
error: { [Error: connect EHOSTUNREACH]
  code: 'EHOSTUNREACH',
  errno: 'EHOSTUNREACH',
  syscall: 'connect' }

/usr/local/lib/node_modules/dsp-w215-hnap-master/node_modules/then-request/node_modules/promise/lib/done.js:10
      throw err;
            ^
Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:11:13
    at DLinkPlug.<anonymous> (/usr/local/lib/node_modules/dsp-w215-hnap-master/index.js:50:13)
    at tryCallOne (/usr/local/lib/node_modules/dsp-w215-hnap-master/node_modules/then-request/node_modules/promise/lib/core.js:37:12)
    at /usr/local/lib/node_modules/dsp-w215-hnap-master/node_modules/then-request/node_modules/promise/lib/core.js:123:15
    at flush (/usr/local/lib/node_modules/dsp-w215-hnap-master/node_modules/then-request/node_modules/promise/node_modules/asap/raw.js:50:29)
    at process._tickCallback (node.js:419:13)
```

IP has not changed (the plug regularly reply if I query it at `http://<IP>/HNAP1`

Note that curl `http://<IP>/HNAP1` from the NAS correctly prints the soap actions list.

Can you help me?

**Comment by bikerp** [comment]
Hi, have you changed something in the dependencies or NodeJS itself?

**Comment by teejay-87** [comment]
Actually no.
It started to fail from one day to the next.
Then I tried to **apt-get upgrade** but the issue remains.

**Comment by teejay-87** [comment]
Plug firmware is currently 2.22.  
I didn't update it, does it update on itself maybe?

**Comment by bikerp** [comment]
This is the latest firmware and I have developed this utility against this version. So this shouln't be an issue. I think you have to  investigate on your own.

**Comment by teejay-87** [comment]
I'll do that.
Anyway there is a new firmware now, 2.23.
