### ISSUE TITLE
Plugin for w115

### ISSUE THREAD

**Issue by ebaderuz** [bikerp/dsp-w215-hnap#13]
Any chance to implement something for DLink DSP-W115?
I tried with this plugin, the accessory is showed into Home app (iOS) and it is connected, but when I turn it ON or OFF nothing happen. Thank you.

**Comment by bikerp** [comment]
If I had the plug I could try. But I don't have one. Sorry.

**Comment by Garfonso** [comment]
> 
> 
> If I had the plug I could try. But I don't have one. Sorry.

If I (we?)'d supply you with one, would that help? 😃 

I have a DSP-W115 (and W215 and DCH-S150 motion detector) and I dug around a bit more. It returns a 500 error on the login action and states that it does not know such an action... 😢 Do you have any idea on how to get information how the action is called now? Or is this a lost cause?

I'd be happy about any hints.

//Edit:
And thank you very much for your initial work. It really helped me to build an adapter for those devices for ioBroker which works very well with the old devices.

**Comment by jonassjoh** [comment]
In case anyone is still interested I created a library to interface with the DSP-W115 and the DSP-W245. You can find the library below.

https://github.com/jonassjoh/dspW245

**Comment by Garfonso** [comment]
As this is node.js I'll add a link to my node.js library as well: https://github.com/Garfonso/dlinkWebSocketClient

And the newer devices are pretty different from the old HNAP1 protocol. On the plus side they notice you about events (socket state, led state, ...?), if you keep the connection open, i.e. you do not have to poll them.
