### ISSUE TITLE
Can turn on but cannot turn off DSP-W110 

### ISSUE THREAD

**Issue by laurence7** [bikerp/dsp-w215-hnap#3]
I stumbled across this code from another site that referred to this Gitbug project. I have the presumably older DSP-W110 1.22 firmware. Using the code here while I can turn on a device attached to the Dlink it won't respond to turn off commands. I can't see any way to see what commands the device responds to since the <ip address>/HNAP1 produces a message saying 
This XML file does not appear to have any style information associated with it. The document tree is shown below.

and there is no  XML below.

Any ideas how to find out what the OFF command string might be?

Thanks

**Comment by laurence7** [comment]
solved - got the wrong code to send to the device

**Comment by biocross** [comment]
@laurence7 Were you able to able get it to work? I'm trying the same thing, can you elaborate a little how did you manage to get this to work?

**Comment by laurence7** [comment]
I did but that was 4 years ago and since then I have lost the code I did. Plus I moved away from that solution over 3 years ago when Amazon Alexa and Google Assistant supported the D-Link device natively.
