### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by crgor** [bikerp/dsp-w215-hnap#5]
Hi,

I have used your code and wrote this in JAVA to automatically read multiple devices temperature, active power and KWH. But after running these devices for more than 5 to 10 days, I have been receiving Internal Server Error 500. 

Tested with the Python code also same result reads successfully for few days and suddenly stops with Internal Server error.

Any Ideas why  ??

**Comment by bikerp** [comment]
Hi, do you mean that the device returned error 500? I have never experienced this error. Maybe you could try to reset the device or update firmware if available.

**Comment by crgor** [comment]
Yes it is, resetting device will make it work normal again. Devices are running on latest firmware V2.22b05.

Actually I have many devices, this reset won't help me. Is there anything else I could try??

**Comment by bikerp** [comment]
I'm sorry but I don't think I can help you with this. Maybe you culd try
Dlink forum.

Dne 24. 8. 2016 9:10 napsal uživatel "crgor" notifications@github.com:

**Comment by bikerp** [comment]
Here is the link to the forum http://forums.dlink.com/index.php?PHPSESSID=3a7t7ngobbu92nbnh5f5koojh1&board=446.0
