### ISSUE TITLE
DSP-W215 power on when run script

### ISSUE THREAD

**Issue by korniza** [bikerp/dsp-w215-hnap#6]
I use DSP-W215 firmware 2.22 (latest) and when I run script, plug powers on.
I think has to do with the code that is send to plug. Is there any way to power on/off the plug from the script selecting by user variant?

**Comment by bikerp** [comment]
Yes the default procedure of the script is to power on the plug and then measure in infinite loop. All the operations are functions contained in the js/soapclient.js script.
