### ISSUE TITLE
Login and password?

### ISSUE THREAD

**Issue by Kageetai** [bikerp/dsp-w215-hnap#9]
Hi there, I am trying to run your package simply to try to turn my smartplug on and off.
But I have no idea, what my ´LOGIN_USER´ and ´LOGIN_PWD´ are supposed to be. I guess they are not the username and password I use to log into the dlink smarthome app, right?

**Comment by bikerp** [comment]
Hi, the username is "admin" and the password is the PIN code that you can see on the sticker provided with the plug.

**Comment by Kageetai** [comment]
Ah okay, this works. Thanks, totally forgot about this sticker.
